### ISSUE TITLE
MSPT instability

### ISSUE THREAD

**Issue by GenifeYouTube** [TECHNOVE/Airplane#20]
Hi, sorry in advance for the bad english.

I have a ryzen 7 5800x server, 32GB DDR4 ram and nvme. On my server, with any optimization, the MSPT value can increase to 1000 (usually 100-600) for no reason and sag occurs.
I checked it on the Akarin core - everything is the best there, there are no drawdowns or problems with MSPT, everything is stable.

**Comment by GenifeYouTube** [comment]
I checked for Tuinity - also unstable MSPT, on the Paper - everything is fine, as well as on Akarin

**Comment by GenifeYouTube** [comment]
I checked it again, on tuinity only when starting a high mspt, then everything is fine. Only the airplane has a problem:(

**Comment by PaulBGD** [comment]
Could you try disabling the multithreaded tracker in `airplane.air`?
