### ISSUE TITLE
No Tile Drops

### ISSUE THREAD

**Issue by AgentLoneStar007** [TECHNOVE/Airplane#22]
Hi. So I play on a server, and occasionally, there are no tile drops from blocks. To my knowledge, the server is 100% vanilla Minecraft.

**Comment by PaulBGD** [comment]
Could you give me a list of plugins, and if possible a video of this happening?

**Comment by AgentLoneStar007** [comment]
Technically, the issue is solved. It fixed immediately after I re-logged. So nevermind.
